name: Build and upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NESTILER_REPO: https://github.com/ClusterM/nestiler
      NESTILER_DIR: nestiler-source
      FDSPACKER_REPO: https://github.com/ClusterM/fdspacker
      FDSPACKER_DIR: fdspacker-source
      NESASM_REPO: https://github.com/ClusterM/nesasm
      NESASM_DIR: nesasm-source
    steps:
    - name: Checkout DupliFDS
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x      
    - name: Checkout NesTiler
      run: |
        git clone ${{ env.NESTILER_REPO }} ${{ env.NESTILER_DIR }}
        cd ${{ env.NESTILER_DIR }}
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        git checkout $LATEST_TAG        
    - name: Build NesTiler
      run: dotnet publish ${{ env.NESTILER_DIR }}/NesTiler -c Release --no-self-contained -r linux-x64 -o ./nestiler
    - name: Checkout FDSPacker
      run: |
        git clone ${{ env.FDSPACKER_REPO }} ${{ env.FDSPACKER_DIR }}
        cd ${{ env.FDSPACKER_DIR }}
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        git checkout $LATEST_TAG        
    - name: Build FDSPacker
      run: dotnet publish ${{ env.FDSPACKER_DIR }}/FDSPacker -c Release --no-self-contained -r linux-x64 -o ./fdspacker
    - name: Checkout nesasm CE
      run: |
        git clone ${{ env.NESASM_REPO }} ${{ env.NESASM_DIR }}
        cd ${{ env.NESASM_DIR }}
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        git checkout $LATEST_TAG        
    - name: Build nesasm CE
      run: make -C ${{ env.NESASM_DIR }}/source EXEDIR=..
    - name: Build DupliFDS
      run: |
        mkdir -p duplifds
        make TILER=./nestiler/nestiler FDSPACKER=./fdspacker/fdspacker NESASM=./nesasm-source/nesasm OUTPUT_IMAGE=./duplifds/duplifds.fds
        cp LICENSE duplifds
        cp README.md duplifds
    - name: Archive
      working-directory: duplifds
      run: |
        sudo apt-get install zip
        zip -r9 duplifds.zip duplifds
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: duplifds
        path: duplifds.zip
